$ANSIBLE_VAULT;1.1;AES256
38323830333063376562376536666139643464663533643035326530623134356332343264643235
6365616664323039326331343566303337636239316434610a316636623637363962303864333534
66383432323138353231343637383639613133366537326433383234333162663638323763626166
3337633462313338320a383666636262373965653832616137646437396238376133323836383438
66653762306561623961663461336136396164323332653039643566306436613236373066326239
6630393965616235626639613439363932333536656638383831
