$ANSIBLE_VAULT;1.1;AES256
32343065303835636463633036623437343339326131376230623062376139316163366164323063
3637623165636331373861373038656163636538353239610a366463323161343836363064666230
66353439656233303436393330303965303332613832633431326234666331666238323739373661
6465663636363731310a643535616564396431383336346335666633366365346438383932643632
63616663343530353066393831306366326336666533336263343635366337356139383735363566
30373936306265653734623835393263343439376333386465343935393164323366386635653064
666139366332663334363165343437363530
