$ANSIBLE_VAULT;1.1;AES256
39376161653463363265386134373731323934303662303533333331613263666365323466333331
6563646466343763316536363166373531623732333062300a383132306461663461656639386366
65666533316661343234356536376634376639303236313366313564333966383036346636636561
6462666563653666310a343732646539313935663938616338316432656532313239363439316163
30353335653962333339626632366637663861343430363333623638373137633436396334396134
38326432626635393332313839326530386637633562653333663539663865373865306538383861
64616361656665373333313233623235356261316162323361333265653265396662376138626537
36373666656262343639353030396232363734636662633662653763643235343335616533623137
39643736633466323932353530656535303331653938653333396530346239336234623866316639
66643131386133323538333863363465383636346236376566623737363838636533306265366439
316465646562373663353136653764313939
