$ANSIBLE_VAULT;1.1;AES256
36646262316632636663636238666364383735303133633639326630346233663561306335636135
3632313834646537643266383661656233373733326232370a333666333339373639643533626135
30316438336465323932643635373539613865653963663935333561313634333964383332333938
6364313561336434630a656334383036356532633331373462656137316266343732323733336334
61663639636566376139383065306161396634376131623865333831386265663734353637353836
36656536386464636235343366343264386335313238613031653131376239356165333232373439
30373834303832343266643036666637383562353630373531363962363931653837306461363461
39343630353464373433356633373963386338653637393831353563663436636565653636373837
3630
