ansible_host_machine:
  ansible_host: flookaa
  ansible_connection: ssh
  ansible_python_interpreter: /usr/bin/python3
  ansible_become: true
  ansible_become_method: sudo
  ansible_become_user: root

server_cert: "/etc/ssl/certs/server.crt"

gateway4: "10.0.0.1"

containers:
  nginx:
    ip: "10.0.0.10"
    ports:
      ssh: 2210
      http: 80
      https: 443
  redis:
    ip: "10.0.0.60"
    ports:
      ssh: 2260
      grpc: 5060
  app: 
    ip: "10.0.0.30"
    ports:
      ssh: 2230
      grpc: 5030
      http: 8080
  postgres:
    ip: "10.0.0.20"
    ports:
      ssh: 2220
      postgres: 5432
  s3:
    ip: "10.0.0.40"
    ports:
      ssh: 2240
      grpc: 5040
      http: 8080
  mongodb:
    ip: "10.0.0.50"
    ports:
      ssh: 2250
      mongo: 27017
  nats:
    ip: "10.0.0.70"
    ports:
      ssh: 2270
      grpc: 5070
      nats: 4222
      http: 8080
  grafana:
    ip: "10.0.0.80"
    ports:
      ssh: 2280
      http: 3000
  neo4j:
    ip: "10.0.0.90"
    ports:
      ssh: 2290
      bolt: 7687

  
  internal_build:
    ip: "10.0.0.100"
    ports:
      ssh: 22100
      http: 57017
